---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clickhouse-com-v1alpha1-clickhousecluster
  failurePolicy: Fail
  name: mclickhousecluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - clickhouse.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clickhouseclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clickhouse-com-v1alpha1-keepercluster
  failurePolicy: Fail
  name: mkeepercluster.kb.io
  rules:
  - apiGroups:
    - clickhouse.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keeperclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clickhouse-com-v1alpha1-clickhousecluster
  failurePolicy: Fail
  name: vclickhousecluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - clickhouse.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clickhouseclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clickhouse-com-v1alpha1-keepercluster
  failurePolicy: Fail
  name: vkeepercluster.kb.io
  rules:
  - apiGroups:
    - clickhouse.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keeperclusters
  sideEffects: None
