## Append samples of your project ##
resources:
- v1alpha1_keepercluster.yaml
- _v1alpha1_keepercluster.yaml
- v1alpha1_clickhousecluster.yaml
- _v1alpha1_clickhousecluster.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
