name: Create release images and GitHub Release
on:
  push:
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ghcr.io/clickhouse
  VERSION: ${{ github.ref_name }}

permissions:
  packages: write
  attestations: write
  id-token: write
  contents: write
  pull-requests: read

jobs:
  release-operator-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build operator image
        run: make docker-buildx

  release-operator-olm-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install jq
        uses: dcarbone/install-jq-action@v3.2.0
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build operator bundle image
        run: make bundle bundle-buildx
      - name: Build catalog
        run: make catalog-buildx
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Mark catalog as latest
        run: make catalog-push-latest

  release-operator-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Verify Helm installation
        run: helm version
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Package helm chart
        run: make package-helmchart
      - name: Build and push helm OCI image
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          make push-helmchart

  create-release:
    runs-on: ubuntu-latest
    needs:
      - release-operator-image
      - release-operator-olm-images
      - release-operator-helm-chart
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Kustomize Build
        uses: karancode/kustomize-github-action@master
        with:
          token: ${{ github.token }}
          kustomize_version: 5.7.1
          kustomize_build_dir: "config/default"
          kustomize_output_file: "dist/clickhouse-operator.yaml"
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Verify Helm installation
        run: helm version
      - name: Package helm chart
        run: make package-helmchart

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Save controller images
        run: make docker-save

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ github.ref_name }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{github.ref_name }}
          draft: true
          body: |
            ## Install using the manifest
            ```
            kubectl apply -f https://github.com/ClickHouse/clickhouse-operator/releases/download/${{github.ref_name}}/clickhouse-operator.yaml
            ```
            
            ## Install using helmchart
            ```
            helm install clickhouse-operator oci://ghcr.io/clickhouse/clickhouse-operator-helm \
               --version=${{env.VERSION}} \
               --create-namespace \
               -n clickhouse-operator-system
            ```
            
            ## Changelog
            ${{steps.build_changelog.outputs.changelog}}
          generate_release_notes: false
          append_body: true
          files: |
            dist/clickhouse-operator.yaml
            clickhouse-operator-helm-${{env.VERSION}}.tgz
            clickhouse-operator_${{env.VERSION}}_*.tar.gz
