name: Create release images and GitHub Release
on:
  push:
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ghcr.io/clickhouse/clickhouse-operator
  VERSION: ${{ github.ref_name }}

permissions:
  packages: write
  attestations: write
  id-token: write
  contents: write

jobs:
  release-operator-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build operator image
        run: make docker-buildx
  release-operator-bundle-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build operator bundle image
        run: make bundle bundle-buildx
  release-operator-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Verify Helm installation
        run: helm version
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Package helm chart
        run: helm package --version ${VERSION} --app-version v${VERSION} dist/chart
      - name: Build and push helm OCI image
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          make push-helmchart
      - name: Push chart and updated index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard
          git fetch origin helm-releases
          git checkout helm-releases
          find .
          helm repo index .
          git add index.yaml
          git add clickhouse-operator-${VERSION}.tgz
          git commit -m "Add chart $VERSION"
          git push origin helm-releases
  create-release:
    runs-on: ubuntu-latest
    needs:
      - release-operator-image
      - release-operator-bundle-image
      - release-operator-helm-chart
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Kustomize Build
        uses: karancode/kustomize-github-action@master
        with:
          token: ${{ github.token }}
          kustomize_version: 5.7.1
          kustomize_build_dir: "config/default"
          kustomize_output_file: "dist/clickhouse-operator.yaml"
      - name: Checkhout chart archive
        run: git fetch origin && git checkout origin/helm-releases -- clickhouse-operator-${VERSION}.tgz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{github.ref_name }}
          body: |
            Pull latest operator images:
            ```
            docker pull ghcr.io/clickhouse/clickhouse-operator/clickhouse-operator:${{ github.ref_name }}
            docker pull ghcr.io/clickhouse/clickhouse-operator/clickhouse-operator-bundle:${{ github.ref_name }}
            ```
            To deploy this release use
            ```
            kubectl apply -f https://github.com/ClickHouse/clickhouse-operator/releases/download/${{github.ref_name}}/clickhouse-operator.yaml
            ```
          generate_release_notes: true
          append_body: true
          files: |
            dist/clickhouse-operator.yaml
            clickhouse-operator-${VERSION}.tgz

